<?php

declare(strict_types=1);

namespace Gutenform\Assets;

/**
 * Class Strings
 *
 * Collects and provides all translatable strings for JavaScript.
 *
 * @package Gutenform\Assets
 */
class Strings
{

	/**
	 * Get all translatable strings as an array.
	 *
	 * @return array Array of translated strings.
	 */
	public static function get_strings(): array
	{
		return array(
			// Common
			'loading' => __('Loading...', 'gutenform'),
			'error' => __('Error', 'gutenform'),
			'errorOccurred' => __('An error occurred', 'gutenform'),
			'save' => __('Save', 'gutenform'),
			'cancel' => __('Cancel', 'gutenform'),
			'delete' => __('Delete', 'gutenform'),
			'edit' => __('Edit', 'gutenform'),
			'create' => __('Create', 'gutenform'),
			'update' => __('Update', 'gutenform'),
			'close' => __('Close', 'gutenform'),
			'yes' => __('Yes', 'gutenform'),
			'no' => __('No', 'gutenform'),
			'copied' => __('Copied', 'gutenform'),
			'copy' => __('Copy', 'gutenform'),
			'copyToClipboard' => __('Copy to clipboard', 'gutenform'),
			'copiedExclamation' => __('Copied!', 'gutenform'),

			// Login Page
			'login' => __('Login', 'gutenform'),
			'loginDescription' => __('Enter your email below to login to your account', 'gutenform'),
			'email' => __('Email', 'gutenform'),
			'password' => __('Password', 'gutenform'),
			'forgotPassword' => __('Forgot your password?', 'gutenform'),
			'loginWithGoogle' => __('Login with Google', 'gutenform'),
			'dontHaveAccount' => __("Don't have an account?", 'gutenform'),
			'signUp' => __('Sign up', 'gutenform'),

			// Error Page
			'oops' => __('Oops!', 'gutenform'),
			'unexpectedError' => __('Sorry, an unexpected error has occurred.', 'gutenform'),

			// Welcome Page
			'addFirstMailProvider' => __('Add your first Mail Provider', 'gutenform'),
			'addFirstMailProviderDesc' => __('Configure an email provider to receive form submissions via email.', 'gutenform'),
			'createFirstMailbox' => __('Create your first Mailbox', 'gutenform'),
			'createFirstMailboxDesc' => __('Organize form submissions into mailboxes for better management.', 'gutenform'),
			'addFirstLabel' => __('Add your first Label', 'gutenform'),
			'addFirstLabelDesc' => __('Create labels to categorize and organize your form entries.', 'gutenform'),
			'createFirstForm' => __('Create your first Form', 'gutenform'),
			'createFirstFormDesc' => __('Build a form using Gutenberg blocks and start collecting submissions.', 'gutenform'),
			'buildYourFirstForm' => __('Build Your first Form', 'gutenform'),
			'createFirstFormDescription' => __('Create your first form using the Gutenberg block editor', 'gutenform'),
			'welcomeToGutenForm' => __('Welcome to GutenForm!', 'gutenform'),
			'loadingChecklist' => __('Loading checklist...', 'gutenform'),
			'view' => __('View', 'gutenform'),
			'setup' => __('Setup', 'gutenform'),

			// Inbox Page
			'inbox' => __('Inbox', 'gutenform'),
			'all' => __('All', 'gutenform'),
			'unread' => __('Unread', 'gutenform'),
			'read' => __('Read', 'gutenform'),
			'starred' => __('Starred', 'gutenform'),
			'unstarred' => __('Unstarred', 'gutenform'),
			'important' => __('Important', 'gutenform'),
			'followUp' => __('Follow Up', 'gutenform'),

			// Settings - General
			'licenseKey' => __('License Key', 'gutenform'),
			'enterLicenseKey' => __('Enter your license key', 'gutenform'),
			'licenseKeyDescription' => __('Enter your Gutenform license key to unlock premium features.', 'gutenform'),
			'settingsSaved' => __('Settings saved', 'gutenform'),
			'settingsSavedDescription' => __('Your general settings have been updated successfully.', 'gutenform'),
			'saveChanges' => __('Save changes', 'gutenform'),
			'licenseKeyRequired' => __('License key is required.', 'gutenform'),

			// Settings - Providers
			'providers' => __('Providers', 'gutenform'),
			'manageProviders' => __('Manage your form submission providers.', 'gutenform'),
			'addProvider' => __('Add Provider', 'gutenform'),
			'createProvider' => __('Create Provider', 'gutenform'),
			'editProvider' => __('Edit Provider', 'gutenform'),
			'providerCreated' => __('Provider created', 'gutenform'),
			'providerCreatedDesc' => __('The provider has been created successfully.', 'gutenform'),
			'providerUpdated' => __('Provider updated', 'gutenform'),
			'providerUpdatedDesc' => __('The provider has been updated successfully.', 'gutenform'),
			'providerDeleted' => __('Provider deleted', 'gutenform'),
			'providerDeletedDesc' => __('The provider has been deleted successfully.', 'gutenform'),
			'confirmDeleteProvider' => __('Are you sure you want to delete this provider?', 'gutenform'),
			'loadingProviders' => __('Loading providers...', 'gutenform'),
			'errorProviders' => __('Error:', 'gutenform'),
			'noProvidersFound' => __('No providers found. Create your first provider to get started.', 'gutenform'),
			'providerType' => __('Provider Type', 'gutenform'),
			'active' => __('Active', 'gutenform'),
			'inactive' => __('Inactive', 'gutenform'),
			'created' => __('Created', 'gutenform'),

			// Settings - Mailboxes
			'mailboxes' => __('Mailboxes', 'gutenform'),
			'manageMailboxes' => __('Manage your mailboxes for form submissions.', 'gutenform'),
			'addMailbox' => __('Add Mailbox', 'gutenform'),
			'createMailbox' => __('Create Mailbox', 'gutenform'),
			'editMailbox' => __('Edit Mailbox', 'gutenform'),
			'mailboxCreated' => __('Mailbox created', 'gutenform'),
			'mailboxCreatedDesc' => __('The mailbox has been created successfully.', 'gutenform'),
			'mailboxUpdated' => __('Mailbox updated', 'gutenform'),
			'mailboxUpdatedDesc' => __('The mailbox has been updated successfully.', 'gutenform'),
			'mailboxDeleted' => __('Mailbox deleted', 'gutenform'),
			'mailboxDeletedDesc' => __('The mailbox has been deleted successfully.', 'gutenform'),
			'confirmDeleteMailbox' => __('Are you sure you want to delete this mailbox?', 'gutenform'),
			'cannotDeleteDefaultMailbox' => __('Cannot delete default mailbox', 'gutenform'),
			'cannotDeleteDefaultMailboxDesc' => __('Please set another mailbox as default before deleting this one.', 'gutenform'),
			'loadingMailboxes' => __('Loading mailboxes...', 'gutenform'),
			'errorMailboxes' => __('Error:', 'gutenform'),
			'noMailboxesFound' => __('No mailboxes found. Create your first mailbox to get started.', 'gutenform'),
			'title' => __('Title', 'gutenform'),
			'titleRequired' => __('Title is required', 'gutenform'),
			'myMailbox' => __('My Mailbox', 'gutenform'),
			'mailboxTitleDescription' => __('A descriptive name for this mailbox.', 'gutenform'),
			'defaultMailbox' => __('Default Mailbox', 'gutenform'),
			'defaultMailboxDescription' => __('Set this mailbox as the default for new form submissions.', 'gutenform'),
			'default' => __('Default', 'gutenform'),
			'createMailboxDescription' => __('Create a new mailbox to receive form submissions.', 'gutenform'),
			'updateMailboxDescription' => __('Update the mailbox details below.', 'gutenform'),
			'defaultMailboxCannotBeDeleted' => __('Default mailbox cannot be deleted', 'gutenform'),
			'deleteMailbox' => __('Delete mailbox', 'gutenform'),

			// Settings - Labels
			'labels' => __('Labels', 'gutenform'),
			'manageLabels' => __('Manage labels for organizing form entries.', 'gutenform'),
			'addLabel' => __('Add Label', 'gutenform'),
			'createLabel' => __('Create Label', 'gutenform'),
			'editLabel' => __('Edit Label', 'gutenform'),
			'labelCreated' => __('Label created', 'gutenform'),
			'labelCreatedDesc' => __('The label has been created successfully.', 'gutenform'),
			'labelUpdated' => __('Label updated', 'gutenform'),
			'labelUpdatedDesc' => __('The label has been updated successfully.', 'gutenform'),
			'labelDeleted' => __('Label deleted', 'gutenform'),
			'labelDeletedDesc' => __('The label has been deleted successfully.', 'gutenform'),
			'confirmDeleteLabel' => __('Are you sure you want to delete this label?', 'gutenform'),
			'loadingLabels' => __('Loading labels...', 'gutenform'),
			'errorLabels' => __('Error:', 'gutenform'),
			'noLabelsFound' => __('No labels found. Create your first label to get started.', 'gutenform'),
			'name' => __('Name', 'gutenform'),
			'nameRequired' => __('Name is required', 'gutenform'),
			'description' => __('Description', 'gutenform'),
			'color' => __('Color', 'gutenform'),
			'colorInvalid' => __('Color must be a valid hex color (e.g., #FF0000)', 'gutenform'),

			// Block Editor - Field Controls
			'globalFieldSettings' => __('Global Field Settings', 'gutenform'),
			'useCustomName' => __('Use custom name', 'gutenform'),
			'useCustomId' => __('Use custom ID', 'gutenform'),
			'placeholder' => __('Placeholder', 'gutenform'),
			'required' => __('Required', 'gutenform'),
			'enterLabel' => __('Enter label', 'gutenform'),
			'enterHelpText' => __('Enter help text', 'gutenform'),
			'id' => __('ID', 'gutenform'),
			'selectAnOption' => __('Select an option...', 'gutenform'),
			'buttonLabel' => __('Button Label', 'gutenform'),
			'successModalHiddenInPreview' => __('Success modal (hidden in preview)', 'gutenform'),
			'toggleSuccessView' => __('Toggle Success View', 'gutenform'),
			'skin' => __('Skin', 'gutenform'),
			'text' => __('Text', 'gutenform'),
			'number' => __('Number', 'gutenform'),
			'phone' => __('Phone', 'gutenform'),
			'url' => __('URL', 'gutenform'),
			'search' => __('Search', 'gutenform'),
			'ageGroups' => __('Age Groups', 'gutenform'),
			'mr' => __('Mr.', 'gutenform'),
			'mrs' => __('Mrs.', 'gutenform'),
			'diverse' => __('Diverse', 'gutenform'),
			'years017' => __('0-17 years', 'gutenform'),
			'years1824' => __('18-24 years', 'gutenform'),
			'years2534' => __('25-34 years', 'gutenform'),
			'years3544' => __('35-44 years', 'gutenform'),
			'years4554' => __('45-54 years', 'gutenform'),
			'years5564' => __('55-64 years', 'gutenform'),
			'years65Plus' => __('65+ years', 'gutenform'),
			'setupYourFirstMailbox' => __('Setup your First Mailbox', 'gutenform'),
			'createCustomMailbox' => __('Create a custom mailbox to organize your form entries', 'gutenform'),
			'areTheLabelsDefaultOk' => __('Are The Labels (default) ok or change something?', 'gutenform'),
			'reviewAndCustomizeLabels' => __('Review and customize your entry labels', 'gutenform'),
			'configureEmailProvider' => __('Configure an email provider to receive form submissions', 'gutenform'),

			// Block Editor - Select Field
			'selectFieldSettings' => __('Select Field Settings', 'gutenform'),
			'basicForm' => __('Basic Form', 'gutenform'),
			'country' => __('Country', 'gutenform'),
			'federalStates' => __('Federal States', 'gutenform'),
			'germany' => __('Germany', 'gutenform'),
			'austria' => __('Austria', 'gutenform'),
			'switzerland' => __('Switzerland', 'gutenform'),
			'france' => __('France', 'gutenform'),
			'italy' => __('Italy', 'gutenform'),
			'spain' => __('Spain', 'gutenform'),
			'netherlands' => __('Netherlands', 'gutenform'),
			'belgium' => __('Belgium', 'gutenform'),
			'poland' => __('Poland', 'gutenform'),
			'czechRepublic' => __('Czech Republic', 'gutenform'),
			'badenWurttemberg' => __('Baden-Württemberg', 'gutenform'),
			'bavaria' => __('Bavaria', 'gutenform'),
			'berlin' => __('Berlin', 'gutenform'),
			'brandenburg' => __('Brandenburg', 'gutenform'),
			'bremen' => __('Bremen', 'gutenform'),
			'hamburg' => __('Hamburg', 'gutenform'),
			'hesse' => __('Hesse', 'gutenform'),
			'mecklenburgWesternPomerania' => __('Mecklenburg-Western Pomerania', 'gutenform'),
			'lowerSaxony' => __('Lower Saxony', 'gutenform'),
			'northRhineWestphalia' => __('North Rhine-Westphalia', 'gutenform'),
			'rhinelandPalatinate' => __('Rhineland-Palatinate', 'gutenform'),
			'saarland' => __('Saarland', 'gutenform'),
			'saxony' => __('Saxony', 'gutenform'),
			'saxonyAnhalt' => __('Saxony-Anhalt', 'gutenform'),
			'schleswigHolstein' => __('Schleswig-Holstein', 'gutenform'),
			'thuringia' => __('Thuringia', 'gutenform'),

			// Dashboard
			'dashboard' => __('Dashboard', 'gutenform'),
			'overview' => __('Overview', 'gutenform'),
			'analytics' => __('Analytics', 'gutenform'),
			'reports' => __('Reports', 'gutenform'),
			'notifications' => __('Notifications', 'gutenform'),
			'totalRevenue' => __('Total Revenue', 'gutenform'),
			'subscriptions' => __('Subscriptions', 'gutenform'),
			'sales' => __('Sales', 'gutenform'),
			'activeNow' => __('Active Now', 'gutenform'),
			'download' => __('Download', 'gutenform'),
			'recentSales' => __('Recent Sales', 'gutenform'),
			'youMadeSalesThisMonth' => __('You made 265 sales this month.', 'gutenform'),
			'fromLastMonth' => __('from last month', 'gutenform'),
			'sinceLastHour' => __('since last hour', 'gutenform'),

			// Inbox
			'junk' => __('Junk', 'gutenform'),
			'archive' => __('Archive', 'gutenform'),
			'trash' => __('Trash', 'gutenform'),
			'noData' => __('No data', 'gutenform'),
			'entryLabels' => __('Entry Labels', 'gutenform'),

			// Providers - Additional strings
			'providerTypeRequired' => __('Provider type is required', 'gutenform'),
			'select' => __('Select', 'gutenform'),
			'myEmailProvider' => __('My Email Provider', 'gutenform'),
			'providerNameDescription' => __('A descriptive name for this provider.', 'gutenform'),
			'selectProviderType' => __('Select a provider type', 'gutenform'),
			'selectProviderTypeDescription' => __('Select the type of provider.', 'gutenform'),
			'formIdentifierOptional' => __('Form Identifier (optional)', 'gutenform'),
			'leaveEmptyForGlobalProvider' => __('Leave empty for global provider', 'gutenform'),
			'formIdentifierDescription' => __('Form-specific provider. Leave empty for global provider that can be used by all forms.', 'gutenform'),
			'enableOrDisableProvider' => __('Enable or disable this provider.', 'gutenform'),
			'manageProvidersDescription' => __('Manage form submission providers (Email, Webhook, etc.).', 'gutenform'),
			'updateProviderDetails' => __('Update the provider details below.', 'gutenform'),
			'configureNewProvider' => __('Configure a new provider for form submissions.', 'gutenform'),
			'type' => __('Type:', 'gutenform'),
			'form' => __('Form:', 'gutenform'),
			'globalProvider' => __('Global Provider', 'gutenform'),

			// Labels - Additional strings
			'manageLabelsDescription' => __('Manage labels for organizing and categorizing form entries.', 'gutenform'),
			'updateLabelDetails' => __('Update the label details below.', 'gutenform'),
			'createNewLabel' => __('Create a new label to organize your form entries.', 'gutenform'),
			'important' => __('Important', 'gutenform'),
			'uniqueNameForLabel' => __('A unique name for this label.', 'gutenform'),
			'optionalDescriptionForLabel' => __('Optional description for this label', 'gutenform'),
			'optionalDescriptionHelp' => __('An optional description to help identify this label.', 'gutenform'),
			'chooseColorForLabel' => __('Choose a color to visually identify this label.', 'gutenform'),

			// Welcome Page - Additional strings
			'letsGetYouStarted' => __("Let's get you started with a few quick steps", 'gutenform'),
			'allSetRedirecting' => __('🎉 All set! Redirecting to inbox...', 'gutenform'),

			// Application Layout
			'pluginName' => __('Plugin Name', 'gutenform'),
			'toggleNavigationMenu' => __('Toggle navigation menu', 'gutenform'),
			'toggleUserMenu' => __('Toggle user menu', 'gutenform'),
			'myAccount' => __('My Account', 'gutenform'),
			'settings' => __('Settings', 'gutenform'),
			'support' => __('Support', 'gutenform'),
			'logout' => __('Logout', 'gutenform'),
			'charts' => __('Charts', 'gutenform'),

			// Options Modal
			'manageOptions' => __('Manage Options', 'gutenform'),
			'syncLabelAndValue' => __('Sync label and value', 'gutenform'),
			'addBulkOptions' => __('Add Bulk Options', 'gutenform'),
			'bulkOptionsPlaceholder' => __('Enter options separated by commas. Use format: Label or Label:value', 'gutenform'),
			'bulkOptionsExample' => __('Example: Red,Blue,Green or Red:red,Blue:blue,Green:green', 'gutenform'),
			'addOptions' => __('Add Options', 'gutenform'),
			'move' => __('Move', 'gutenform'),
			'label' => __('Label', 'gutenform'),
			'value' => __('Value', 'gutenform'),
			'actions' => __('Actions', 'gutenform'),
			'newLabel' => __('New label...', 'gutenform'),
			'newValue' => __('New value...', 'gutenform'),
			'add' => __('Add', 'gutenform'),
			'selected' => __('selected', 'gutenform'),
			'deleteSelected' => __('Delete Selected', 'gutenform'),
			'chooseTemplateOrStartEmpty' => __('Choose a template or start empty', 'gutenform'),
			'startWithoutTemplate' => __('Start without template', 'gutenform'),
			'options' => __('Options:', 'gutenform'),
		);
	}
}
