export const allowedBlocks = [
	'gutenform/input',
    'gutenform/textarea',
    'gutenform/submit',
    'core/columns',
    'core/column',
    'core/heading',
    'core/paragraph',
    'core/image',
    'core/list',
    'core/list-item',
    'core/quote',
    'core/table',
    'core/video',
    'core/embed',
    'core/group',
];